### PR TITLE
Parse shelter_api and save random 20 to database

### PR DESCRIPTION
**Pull request by CraigCCC**
Add lib/tasks/shelter_api.rake

### CODE REVIEW

**Review by wayne2753 — COMMENTED** [review]
ok to me

**Comment by zasaeve** [comment]
ok~

**Comment by jasonj27** [comment]
Lgtm

**Review by jasonj27 — APPROVED** [review]

**Review by wayne2753 — COMMENTED** [review]
lgtm

**Review by wayne2753 — APPROVED** [review]

**Review by zasaeve — APPROVED** [review]

**Pull request merged**
